name: Ubuntu (gcc)

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
    
jobs:
  ubuntu_gcc:
    strategy:
      matrix:
        mode: [ Debug, Release ]
        cpp_version: [11, 20]
    runs-on: ubuntu-22.04
    
    steps:
    - name: check out
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install curl libssl-dev libcurl4-openssl-dev

    - name: checkout gcc version
      run: gcc --version

    - name: configure cmake
      run: CXX=g++ CC=gcc cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }}
      
    - name: build project
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.mode }}
